import numpy as np

# CONSTANTS VALUES FOR IMAGE RESTORATION MODEL
CONST_STR_IMAGE_NAME = 'image'
CONST_STR_EMBED_NAME = 'embedding'
CONST_STR_RESTO_NAME = 'output'

CONST_TUPLE_IMAGE = (1, 3, 360, 640)
CONST_TUPLE_EMBED = (1, 324)
CONST_TUPLE_RESTO = (1, 3, 360, 640)

CONST_TYPE_DATA = np.float32